# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_remove_item_description_alter_item_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
