# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_item_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_count", models.IntegerField(default=0)),
                ("max_access_count", models.IntegerField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shares", to="items.item")),
            ],
            options={
                "db_table": "shared_items",
                "indexes": [
                    models.Index(fields=["token"], name="items_shared_item_token_idx"),
                    models.Index(fields=["-created_at"], name="items_shared_item_created_idx"),
                ],
            },
        ),
    ]
