# Generated by Django 5.2.10 on 2026-01-23 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_shareditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-is_pinned', '-created_at')},
        ),
        migrations.RenameIndex(
            model_name='shareditem',
            new_name='shared_item_token_ab9831_idx',
            old_name='items_shared_item_token_idx',
        ),
        migrations.RenameIndex(
            model_name='shareditem',
            new_name='shared_item_created_dda3c6_idx',
            old_name='items_shared_item_created_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', '-is_pinned'], name='items_user_id_fedca5_idx'),
        ),
    ]
