# Generated by Django 5.2.10 on 2026-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_shareditem_slug_and_password'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shareditem',
            new_name='shared_item_slug_16696f_idx',
            old_name='items_shared_slug_idx',
        ),
    ]
