# Generated by Django 5.2.10 on 2026-01-22 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('items_backed_up', models.PositiveIntegerField(default=0)),
                ('files_backed_up', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Log',
                'verbose_name_plural': 'Backup Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_hours', models.PositiveIntegerField(default=24, help_text='Backup interval in hours')),
                ('backup_on_new_item', models.BooleanField(default=True, help_text='Only backup if new items added')),
                ('s3_enabled', models.BooleanField(default=False)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=255)),
                ('s3_access_key', models.CharField(blank=True, max_length=255)),
                ('s3_secret_key', models.CharField(blank=True, max_length=255)),
                ('s3_region', models.CharField(default='us-east-1', max_length=100)),
                ('s3_endpoint', models.CharField(blank=True, help_text='Custom S3 endpoint (optional)', max_length=255)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_item_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Settings',
                'verbose_name_plural': 'Backup Settings',
            },
        ),
    ]
