# Generated by Django 5.2.10 on 2026-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='local_backup_enabled',
            field=models.BooleanField(default=False, help_text='Enable local backup to filesystem'),
        ),
    ]
